
services:
  node-express-app:  # Service name
    container_name: node-express-app  # Optional: Name of the container
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    env_file:
      - ./.env  # Load envir variables from .env file
  mongo:  #ready image
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example   
volumes:
    mongo-db:

    