version: '3'
services:
  node-express-app:
    build: 
      context: .  # ✅ This tells Docker to use the Dockerfile in the current directory
      args:
        - NODE_ENV=development
    environment:
      NODE_ENV: development
    ports:
      - "8000:8000"  # ✅ Exposes port 8000
    command: ["npm", "start"]
